print("#################################\n")
print("#                               #\n")
print("#      Rika Fauliana Rahmi      #\n")
print("#         2410817120017         #\n")
print("#                               #\n")
print("#################################")